name: 🚀 Deploy on Tag (Simulated on Localhost)

on:
  push:
    tags:
      - '*'  # runs on **any** tag push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Simulate Build
        run: |
          echo "🔧 Building application..."
          mkdir -p dist
          echo "Version: $GITHUB_REF" > dist/version.txt
          cat dist/version.txt

      - name: Simulate Tests
        run: |
          echo "✅ Running tests..."
          echo "All tests passed!"

      - name: Simulate Deployment
        run: |
          echo "🚀 Deploying version $GITHUB_REF to localhost (simulated)"
          echo "📦 Deployment complete!"
