name: 🚀 Deploy on Tag (Simulated on Localhost)

on:
  push:
    tags:
      - '*'  # Triggers for any new tag

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python (simulate environment)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Simulate Build
        run: |
          echo "🔧 Building the application..."
          mkdir -p dist
          echo "Version: $GITHUB_REF" > dist/version.txt
          cat dist/version.txt

      - name: Simulate Tests
        run: |
          echo "✅ Running fake tests..."
          echo "All tests passed successfully."

      - name: Simulate Deployment
        run: |
          echo "🚀 Deploying version $GITHUB_REF to localhost (simulated)..."
          echo "📦 Build complete. ✅ Deployment simulated on your laptop!"
